/*
 * This file is generated by jOOQ.
 */
package com.pady.todo.jooq.tables.references


import com.pady.todo.jooq.tables.Todo
import com.pady.todo.jooq.tables.User



/**
 * The table <code>TODO</code>.
 */
val TODO: Todo = Todo.TODO

/**
 * The table <code>USER</code>.
 */
val USER: User = User.USER
